### ISSUE TITLE
open and save local pau.gz files

### ISSUE THREAD

**Issue by levush** [dfrits/MobilePauker2#14]
No need for dropbox and other related cloud shit.
Just support open for read and write with pau.gz files
The files the original java based pauker uses.
These are unicode test files.
Sopport open, read, write, save as.
People who are using other peoples computers aka as cloud shit can use a generic file ecplorer to move files from or to their favorite cloud service.

And include all pau.gz files on source forge (saved) lessons as local storage where the user can erase unwanted lessons if space is really tight.

Dont bloat software use basic apis and basic functionality

**Comment by RubenKelevra** [comment]
If you have no need for dropbox, that's fine. But a cloud service integration is nice and it's working flawlessly.

If you prefer local files, it's a choice you do for yourself. Expecting that other people change their programs just for your liking on the other hand is pretty narcissistic.

Stop cursing in bug reports would probably also help to honour your feedback.

If this is my project I would close this, just because of your tone.

**Comment by dfrits** [comment]
Sorry for my late reply.

RubenKelevra is right. Please write something like in a more kindly tone. 

Now to your "suggestion": There is an older App for this without cloud integration but the way you described and didn't worked. If you want that you can move the files with the file explorer from your Android phone as you like. The Folder is open and easy to find!
